### PR TITLE
Update CI for docker builds

### PR DESCRIPTION
**Pull request by jonathangreen**
## Description

This PR makes a couple changes to the CI in our repo around how docker containers are built:
- It removes the workflow that we had previously that would remove old tags from docker hub. This doesn't work with the new method of tagging, and docker hub expires old images anyway. 
- It changes how images are tagged
- It removes the upstream testing workflow, in favour of our workflow that publishes docker images

This should assist us in deploying our own releases of the CM as we move forward splitting code away from NYPL.

## Motivation and Context

This updates the github CI to perform the following actions on pushes to this repo:
- Run the tests for circulation
- Run the tests for core
- If both of those pass then
- Build and push docker containers to the [LYRASIS docker hub](https://registry.hub.docker.com/u/lyrasis)

This is different than how the NYPL docker builds work as it builds docker images for every branch in the repo. This should make it easier for us to deploy a particular feature branch out to a client for testing before it is merged into the code base. 

Docker tags are generated by the [ghaction-docker-meta](https://github.com/crazy-max/ghaction-docker-meta) action. This action provides a lot of configuration as to how tags are generated for docker images. This PR uses the following configuration:

For a git branch:
- a tag is created with the `sha-` prefix for the sha of the git commit the tag was built with
- a tag is created / updated with the branch name that the commit came from

For a git tag:
- The `latest` tag is updated
- A tag of the format {major}.{minor} is created / updated
- A tag of the format {major}.{minor}.{fix} is created
- A tag with the hash of the commit used to create it as above

These tags are pushed into each of the three images: [`circ-scripts`](https://registry.hub.docker.com/r/lyrasis/circ-scripts/tags?page=1&ordering=last_updated), [`circ-webapp`](https://registry.hub.docker.com/r/lyrasis/circ-webapp/tags?page=1&ordering=last_updated), and [`circ-exec`](https://registry.hub.docker.com/r/lyrasis/circ-exec/tags?page=1&ordering=last_updated).

You can see how that looks by looking at each of the dockerhub repos above. For the git branch that this PR comes from there are two docker tags created:
- `sha-cac4b3b`
- `update_docker_build`

### CODE REVIEW

**Comment by jonathangreen** [comment]
@tdilauro I think these build give the information you were looking for about exactly what commit the docker container was built against in a couple ways. If you look through the github actions output you can both see the hash it was build against and the hash it pushed into docker hub. And probably easier for pulling into our playbooks, we can directly reference the sha tag that gets pushed.

**Comment by jonathangreen** [comment]
I'd like to capture the information about the the docker builds in notion. I'll turn the PR message here into a page in notion with some details about the docker builds once its merged. I wanted to get feedback and incorporate any changes into the PR before writing those notion docs.

**Comment by jonathangreen** [comment]
I also added to this PR to run these tests on PR as well as push. I did this because I noticed that PRs from pull bot are not getting tests run on them: 
https://github.com/lyrasis/simplye-circulation/pull/11

I think having tests run on these will be helpful in the future. The solution I came up with is a bit messy, as it ends up showing the skipped checks in the status for the PR. I think this is still probably preferable to running the checks twice on internal branches.

**Comment by tdilauro** [comment]
> @tdilauro I think these build give the information you were looking for

This is even better. I don't need to look into layers. The name is the thing it names.

**Comment by tdilauro** [comment]
With regard to "latest" tag: Do we want that updated with every build? As as potential outside consumer of these images, I would want latest to follow releases, so that I know I can rely on it to get an image that is intended for public consumption.

Also, I don't see a "latest" tag in the [most recent builds](https://hub.docker.com/r/lyrasis/circ-scripts/tags?page=1&ordering=last_updated&name=latest), so maybe I'm misunderstanding how the default flavors `latest=auto` is working here.

**Comment by jonathangreen** [comment]
Agreed about the `latest` tag. It should only be getting updated when a tag is pushed into the repo. Not on every build. Presumably every tag will be a new version, so I think that does what we want it to do. Branches won't update the `latest` tag. This isn't super clear in the docker-meta docs, but I think [this section](https://github.com/crazy-max/ghaction-docker-meta#latest-tag) covers it.

**Comment by tdilauro** [comment]
Thanks! That clarification was helpful. I had read your main PR comment and the relevant section on ghaction-docker-meta, but was conflating git and docker tags.

**Comment by jonathangreen** [comment]
I didn't notice the overloading of the word tag when I was writing the PR request. I updated the PR comments to disambiguate a bit and make it more clear where each tag is coming from.

**Review by tdilauro — APPROVED** [review]
This looks good!

**Pull request merged**
